[build]
  command = "pnpm build"
  publish = "dist"

# 代理配置 - 将 /fapig 请求代理到聚合数据 API
[[redirects]]
  from = "/fapig/*"
  to = "http://apis.juhe.cn/fapig/:splat"
  status = 200
  force = true

# SPA 路由配置 - 所有非 API 请求都重定向到 index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API 请求的 CORS 头部配置
[[headers]]
  for = "/fapig/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"

# 静态资源缓存配置
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 安全头部配置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
